Luxeradio-portfolio-landing-section
canopas/canopas-website pull request #172
Opened 2022-05-30 09:04 UTC by cp-priyanka-g

2022-06-08 08:42 UTC, cp-sumi-k requested changes

2022-06-08 08:42 UTC, cp-sumi-k commented on vue-frontend/src/components/partials/ScreenHeaderV2.vue
> +                    ? 'show-links'
As we are hiding link, name should be relatable

2022-06-08 08:43 UTC, cp-sumi-k commented on vue-frontend/src/components/partials/ScreenHeaderV2.vue
> +        <div class="navbar-collapse show-header">
What is `show-header` usage?

2022-06-08 08:43 UTC, cp-shruti-s commented
landing_background.webp image is needed ??

2022-06-08 08:45 UTC, cp-priyanka-g commented
> 



> landing_background.webp image is needed ??

it is used in landing section of home-new page

2022-06-14 10:39 UTC, cp-sumi-k commented
Add text animation as per cuberto

2022-06-15 10:16 UTC, cp-sumi-k approved these changes

2022-06-15 10:16 UTC, cp-shruti-s approved these changes

2022-06-15 10:17 UTC, merged