Add analytics events on jobs page
canopas/canopas-website pull request #277
Opened 2022-10-07 04:08 UTC by cp-priyanka-g

2022-10-07 08:50 UTC, cp-sumi-k requested changes

2022-10-07 08:50 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/CareerView.vue
> +    sendEvent() {
Do we need this here?

2022-10-07 08:50 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/VirtuesView.vue
> +          event: "hover_virtue",
As all events name are same, we can directly apply

2022-10-07 08:50 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/WhyCanopas.vue
> +    window.addEventListener("scroll", this.handleScroll, this.sendEvent);
Is this working?
Also we don't need it as you have already added refs and same code in index page

2022-10-07 08:50 UTC, cp-sumi-k commented on vue-frontend/src/pages/jobs/[id].vue
>      this.$gtag.event("view_page_job_detail");
Remove `view_page_job_detail` event

2022-10-07 08:59 UTC, cp-priyanka-g commented on vue-frontend/src/utils.js
> +    readmore: "view_job_read_more",
Please check on  pages/jobs/[id].vue  line 75

2022-10-07 10:16 UTC, cp-sumi-k requested changes

2022-10-07 10:16 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/VirtuesView.vue
> +      event: "",
Remove this

2022-10-07 10:16 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/WhyCanopas.vue
> -  mounted() {
I think we need `handleScroll`

2022-10-07 10:16 UTC, cp-sumi-k commented on vue-frontend/src/components/partials/ScreenHeaderV2.vue
> +          event: this.isJobsUrl ? "tap_jobs_header_home" : "",
Will it send event if it is  " "?

2022-10-07 10:16 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/FaqSection.vue
> -  mounted() {
I think we need `handleScroll`

2022-10-07 12:07 UTC, cp-sumi-k requested changes

2022-10-07 12:07 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/PerksAndBenifits.vue
> +      event: "",
Remove this.
Once any comment is added, then check for all occurrences. It's not about just that code only.

2022-10-07 12:07 UTC, cp-sumi-k commented on vue-frontend/src/components/partials/ScreenHeaderV2.vue
> +          event: "tap_header_view_career_page ",
Remove space

2022-10-07 12:07 UTC, cp-sumi-k commented on vue-frontend/src/components/partials/ScreenHeaderV2.vue
> +          event: "tap_jobs_header_home",
You have to check `isJobsUrl` here.
But have to add condition in `sendEvent` that `event != " "`

2022-10-07 13:17 UTC, cp-shruti-s approved these changes

2022-10-10 06:10 UTC, cp-sumi-k requested changes

2022-10-10 06:10 UTC, cp-sumi-k commented on vue-frontend/src/utils.js
> +    landingview: "view_jobs_landing_section",
Should it be inside the `portfolios`?

2022-10-10 06:10 UTC, cp-sumi-k commented on vue-frontend/src/pages/jobs/index.vue
> +    this.$gtag.event("view_page_jobs");
Remove this event,as we have added event component wise

2022-10-10 10:03 UTC, cp-sumi-k approved these changes

2022-10-10 10:03 UTC, merged