Add missing analytical events and add design-rush icon in footer section
canopas/canopas-website pull request #280
Opened 2022-10-17 05:56 UTC by cp-priyanka-g

2022-10-17 08:44 UTC, cp-sumi-k requested changes

2022-10-17 08:44 UTC, cp-sumi-k commented on vue-frontend/src/pages/jobs/[id].vue
> +  @apply tw-flex tw-items-center tw-w-[23px] tw-h-[25px] tw-ml-[1.5px];
In width < 438, let's make 2 rows each containing 4 icons

2022-10-17 08:48 UTC, cp-shruti-s commented on vue-frontend/src/pages/portfolio/index.vue
> +    <Portfolio ref="portfoliopage" />
I think we don't need add over here !!

2022-10-18 04:13 UTC, cp-priyanka-g commented on vue-frontend/src/pages/portfolio/index.vue
> +    <Portfolio ref="portfoliopage" />
Sumita told "Its correct".

2022-10-18 11:17 UTC, cp-sumi-k requested changes

2022-10-18 11:17 UTC, cp-sumi-k commented on vue-frontend/src/pages/jobs/[id].vue
> +  @apply tw-flex tw-items-center tw-w-[23px] tw-h-[25px] tw-ml-[1.5px];
Why do we need this? Height and width are not used. Refer attachment below

![Screenshot from 2022-10-18 16-44-41](https://user-images.githubusercontent.com/69897605/196414952-b758c19d-1bfe-40d4-8ad1-6f53f320b298.png)

2022-10-19 02:48 UTC, cp-sumi-k approved these changes

2022-10-19 02:49 UTC, merged