Client review section
canopas/canopas-website pull request #294
Opened 2022-12-23 08:26 UTC by cp-priyanka-g

2023-01-06 10:05 UTC, cp-sumi-k requested changes

2023-01-06 10:05 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ClientReview.vue
> +            "md:tw-w-[510px] lg:tw-w-[75%] xl:tw-w-[81%] 2xl:tw-w-[70%]",
No need to add custom width for all widths. Add some x-padding common to all widths.

2023-01-06 10:07 UTC, cp-priyanka-g commented on vue-frontend/src/assets/css/tailwind.css
> +  font-style: normal;
![image](https://user-images.githubusercontent.com/98794636/210978781-3bfa64ca-dc6d-42ed-aba1-87fcc03c4334.png)
Its there in figma.

2023-01-06 11:12 UTC, cp-priyanka-g commented on vue-frontend/tailwind.config.cjs
> +          "linear-gradient(transparent, transparent),linear-gradient(transparent, transparent),linear-gradient(to right, #FFECEC, #FFECEC)",
yes, because its background-image and it has only linear-gradient property to apply underline that's why i have used in this way
.

2023-01-06 12:46 UTC, cp-sumi-k commented on vue-frontend/tailwind.config.cjs
> +          "linear-gradient(transparent, transparent),linear-gradient(transparent, transparent),linear-gradient(to right, #FFECEC, #FFECEC)",
Can't you apply `bg-[#FFECEC]` directly?

2023-01-09 10:22 UTC, cp-sumi-k requested changes

2023-01-09 10:22 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ClientReview.vue
> +            to deal with tough issues on our app,\s
Match whole slide with figma. Its not same as figma

2023-01-09 10:22 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ClientReview.vue
> +                    class="tw-font-inter-light md:tw-font-inter-regular tw-opacity-80 tw-text-[0.5rem] md:tw-text-[0.625rem] tw-leading-[1.375rem]"
Font size is 12px on large devices.

2023-01-09 10:22 UTC, cp-sumi-k commented on vue-frontend/tailwind.config.cjs
> +        "inter-semibold": ["Inter-Semibold"],
The font-family name should be the same as a tailwind.css font class.  Its `SemiBold` not `Semibold`

2023-01-09 10:32 UTC, cp-sumi-k requested changes

2023-01-09 10:32 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ClientReview.vue
> +                  class="tw-font-inter-light tw-text-[0.75rem] md:tw-text-[1.25rem] tw-leading-[1.375rem] tw-text-black-core"
font-color is not pure black anywhere. Also match font-color of all divs. Its not same as figma

2023-01-10 07:48 UTC, closed without merging