Feat:Create Contribution Section
canopas/canopas-website pull request #304
Opened 2023-01-20 10:00 UTC by cp-priyanka-g

[contribution-section.zip](https://github.com/canopas/canopas-website/files/10465224/contribution-section.zip)
**Tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-01-20 11:20 UTC, cp-sumi-k requested changes

2023-01-20 11:20 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +import introShowCase from "@/assets/images/contribution/animations/introShowCase.gif";
Lets keep first letter capital as others

2023-01-20 11:20 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +          description: "The missing typesafe SwiftUI navigation library.",
Replace with `Highlight different features of the app using Jetpack Compose`

2023-01-20 11:20 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +            "An implementation of Intro Showcase from the Material Design guidelines.",
Replace with `The missing typesafe SwiftUI navigation library`

2023-01-20 11:20 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +            "This repository contains different animations implemented using tailwind css.",
`Cool animations implemented with Tailwind CSS`

2023-01-20 11:20 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +          description: "Cool animations implemented with SwiftUI.",
Let's remove full stop `.`

2023-01-20 11:20 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +                <span
This section is wider in figma

2023-01-20 11:20 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +                      class="tw-mr-2.5 tw-w-[16px] md:tw-w-[30px] lg:tw-w-10 tw-h-[16px] md:tw-h-[30px] lg:tw-h-10 tw-text-pink-300"
Width and height is 28 in desktop

2023-01-20 11:20 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +              class="tw-flex tw-flex-row tw-justify-between tw-mt-[10px] md:tw-mt-[30px] tw-font-inter-regular tw-text-[1rem] tw-leading-[1.5rem] tw-text-black-core/[0.87]"
Font size is 10px in mobile. Also, the design is the same as figma on mobile devices. Check design and all the sizes for the whole section

2023-01-24 08:48 UTC, cp-sumi-k requested changes

2023-01-24 08:48 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ContributionSection.vue
> +          class="tw-flex tw-flex-col tw-basis-[40%] md:tw-basis-[55%] lg:tw-basis-[35%] tw-my-auto tw-bg-[#FFFFFF] tw-p-2.5 sm:tw-p-4 v2-title-3-text tw-shadow-[0_0px_10px_rgba(0,0,0,0.1)]"
What is the use of the `v2-title-3-text` class as we are adding font size classes separately?

2023-01-24 09:15 UTC, cp-jagruti-a approved these changes

2023-01-24 09:17 UTC, cp-sumi-k approved these changes

2023-01-24 09:17 UTC, merged