Do refactoring in service , footer, header  section and change some images to improve quality
canopas/canopas-website pull request #308
Opened 2023-01-27 05:56 UTC by cp-jagruti-a

**Tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-01-27 12:23 UTC, cp-sumi-k requested changes

2023-01-27 12:23 UTC, cp-sumi-k commented on vue-frontend/src/components/partials/NewHeader.vue
> +    this.navContainerHeight = this.$refs.mainHeader.clientHeight + 30;
Space somewhat large, decrease it to 25 or 28

2023-01-27 12:23 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +                  >I'll invest</label
![Screenshot from 2023-01-27 17-32-13](https://user-images.githubusercontent.com/69897605/215082014-27a7cdc2-0326-405d-82fe-d18cf0fb597d.png)
Can take ref from https://codepen.io/dannibla/pen/amgRNR
Fix top space. Also top space of `send me NDA ` is too much, make all fields top space identical
Refactor logic accordingly

2023-01-27 12:23 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/ServiceSectionMobile.vue
> +import circle5 from "@/assets/images/why/why-canopas-mobile-5.webp";
Do space changes

2023-01-27 12:23 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/CTASection.vue
> +            class="tw-flex tw-w-max tw-items-center tw-rounded-full tw-py-3 tw-px-3 gradient-btn consultation-btn"
Refactor `Talk to our experts` button also

2023-01-27 12:23 UTC, cp-sumi-k commented
`pointer` changes not done in the blogs section

2023-01-30 10:26 UTC, cp-sumi-k requested changes

2023-02-01 09:00 UTC, cp-priyanka-g submitted a review, later dismissed

2023-02-02 10:35 UTC, cp-sumi-k approved these changes

2023-02-02 10:36 UTC, merged