Redesign contact page
canopas/canopas-website pull request #313
Opened 2023-02-03 10:56 UTC by cp-priyanka-g

**Tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-02-16 09:23 UTC, cp-sumi-k requested changes

2023-02-16 09:23 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +    reloadWindow() {
We don't need this method in the contact form, we need it in the home page footer to scroll to the top after submitting the form

2023-02-20 08:59 UTC, cp-sumi-k requested changes

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +              class="tw-relative tw-items-center tw-justify-between tw-my-3 tw-mx-0 tw-w-full tw-pt-7 tw-px-0 tw-text-left tw-border-b tw-border-slate-400 tw-bg-none tw-font-inter-regular tw-text-[1r
Fix order of classes

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactLanding.vue
> +          <span
Bullets and text are not aligned properly

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +              <input
Click on it not working properly.

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +                <ul
Background and font color and size should be matched with other fields. Also, it should be below or aligned with the bottom line of the input field. Currently its above the line, not looking perfact

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +                v-model="name"
There should be space between the label and input like I'll invest field, See the image below

![Screenshot from 2023-02-20 14-25-20](https://user-images.githubusercontent.com/69897605/220058630-0c765a54-10c8-428c-b049-19632dba46cb.png)

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +                  <span class="v2-canopas-gradient-text">Call</span>
`Mail` button is by default active, but when we click on `call` it should be active

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +    <div v-if="openCalendlyIframeModal">
It is not opening on `schedule a meeting `click

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +    <div v-if="showSuccessMessagePopup">
Button is not closing

2023-02-20 08:59 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +                    @click.prevent="reloadWindow()"
Remove it

2023-02-20 09:32 UTC, cp-jagruti-a commented on vue-frontend/src/components/contact/NewContactLanding.vue
> +            class="tw-mt-1 tw-mr-[15px] tw-w-[6px] tw-h-[6px] tw-rounded-full tw-bg-gradient-to-b tw-from-pink-300 tw-to-orange-300"
Bullets are little bit bigger in figma

2023-02-20 09:37 UTC, cp-jagruti-a commented on vue-frontend/src/components/contact/NewContactForm.vue
> +              <label class="contactLabel2"
Space between call and mail button should be less according to figma

2023-02-20 09:39 UTC, cp-jagruti-a commented on vue-frontend/src/components/contact/NewContactForm.vue
> +                <button
This Button's  size and padding is not according to figma

2023-02-20 09:44 UTC, cp-jagruti-a commented on vue-frontend/src/components/contact/NewContactForm.vue
> +              <label
There is too much space between i'll invest and NDA

2023-02-22 08:48 UTC, cp-jagruti-a commented on vue-frontend/src/components/contact/NewContactForm.vue
> +              <label class="contactLabel2"
need to look on spacing between this buttons in all devices and they should be in center in mobile devices

2023-02-23 04:26 UTC, cp-jagruti-a submitted a review, later dismissed

2023-02-23 09:00 UTC, cp-sumi-k requested changes

2023-02-24 04:53 UTC, cp-priyanka-g commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +              v-if="this.email && showValidEmailError"
yes, we have define that variable in data() so we can access it.

2023-02-24 08:51 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +              v-if="this.email && showValidEmailError"
this keyword can not accessible in the template, we have to call it as `email` not `this.email`

2023-02-24 08:55 UTC, cp-priyanka-g commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +              v-if="this.email && showValidEmailError"
![image](https://user-images.githubusercontent.com/98794636/221135423-67e22162-570f-4833-9929-5f22b1991c51.png)
i have taken reference from here.

2023-02-24 09:23 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +              v-if="this.email && showValidEmailError"
Try calling trim() function on `this.email` in template

2023-02-24 10:45 UTC, cp-sumi-k submitted a review, later dismissed

2023-03-01 09:11 UTC, cp-sumi-k requested changes

2023-03-01 09:11 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +                  (name.trim().length === 0 && showNameValidationError)
Need to use an `event` in place of the `name` instead of all these conditions. Vue3 is working in that way only

2023-03-03 10:14 UTC, cp-sumi-k requested changes

2023-03-03 10:14 UTC, cp-sumi-k commented on vue-frontend/src/pages/jobs/apply/[id].vue
> +        console.log(formData);
Remove log

2023-03-06 04:58 UTC, cp-sumi-k requested changes

2023-03-06 04:58 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +                    this.NDA = "";
Is this type is bool or string?

2023-03-06 04:58 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +                      this.name = "";
Shouldn't form reset code can be commonized if it's in both` if__else` cases

2023-03-06 04:58 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +                      this.NDA = "";
NDA is string or bool?

2023-03-06 04:58 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +      if (!this.validateForm()) {
form submit is only working when NDA is true, is showing 400 when NDa is false

2023-03-06 05:34 UTC, cp-sumi-k requested changes

2023-03-06 05:34 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/NewContactForm.vue
> +                .then(() => {
Can't we call `this.resetForm();` after then() instead of putting it in both if and else loop?

2023-03-06 05:34 UTC, cp-sumi-k commented on vue-frontend/src/pages/jobs/apply/[id].vue
> +                  (this.fullName = ""),
Fix syntax

2023-03-06 05:37 UTC, cp-sumi-k requested changes

2023-03-06 05:37 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +                    this.invest = "";
Field remains floated after reseting form

2023-03-06 05:50 UTC, cp-sumi-k commented on vue-frontend/src/components/contact/ContactFormFooter.vue
> +                    this.invest = "";
Compare `i'll invest` label with other labels after resting form

2023-03-06 10:13 UTC, cp-jagruti-a approved these changes

2023-03-06 10:14 UTC, cp-sumi-k approved these changes

2023-03-06 10:15 UTC, merged