Enhance : Redesign Portfolio page
canopas/canopas-website pull request #327
Opened 2023-02-17 07:05 UTC by cp-jagruti-a

**Tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-02-17 08:37 UTC, cp-priyanka-g commented on vue-frontend/src/pages/portfolio/index.vue
> +      class="tw-text-center v2-header-text tw-font-futura-bold tw-mt-8 lg:tw-mt-36"
follow guideline for class order.

2023-02-17 08:40 UTC, cp-sumi-k requested changes

2023-02-17 08:40 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/NewPortfolioCTASection.vue
> +<template>
Rename this file as `PortfolioPageCTASection`

2023-02-17 08:40 UTC, cp-sumi-k commented on vue-frontend/src/pages/portfolio/index.vue
> +    <div
You can take the whole portfolio section from the home page. Just replace CTA section based on URL.

2023-02-17 08:40 UTC, cp-sumi-k commented on vue-frontend/src/pages/portfolio/index.vue
> +      navbars: [
This can be reducible if you take portfolio section from home page

2023-02-17 08:40 UTC, cp-sumi-k commented on vue-frontend/src/pages/portfolio/index.vue
> +        newPortfolio: "view_portfolio_section",
Make sure events are available for all sections

2023-02-17 08:49 UTC, cp-priyanka-g commented on vue-frontend/src/components/home-new/NewPortfolioCTASection.vue
> +            class="xl:tw-w-[85%] tw-pt-6 tw-pb-8 tw-text-black-core/[0.6] tw-font-inter-regular tw-text-[0.875rem] tw-leading-[1.125rem] md:tw-text-[1.125rem] md:tw-leading-[1.375rem] xl:tw-text-[1.3
witdh is not required here for large devices, as this paragraph is not looking as figma.

2023-02-17 10:29 UTC, cp-sumi-k requested changes

2023-02-17 10:29 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/CaseStudy.vue
> +      <h1
Let's make it `h2`. Only one h1 tag is allowed per page

2023-02-17 10:29 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/CaseStudy.vue
> +      class="tw-text-center v2-header-text tw-font-futura-bold tw-mt-8 tw-pb-9 md:tw-pb-20 lg:tw-mt-36"
Let's not use `v2-header-text`, because the line height is not proper. Line height should be greater then text-size

2023-02-17 10:29 UTC, cp-sumi-k commented on vue-frontend/src/components/home-new/PortfolioPageCTASection.vue
> +      class="tw-container tw-flex tw-flex-col lg:tw-flex-row xl:tw-max-w-[1878px] lg:tw-h-[390px] xl:tw-h-full"
Let's not use hardcoded height and widths, use container and flex instead

2023-02-20 07:39 UTC, cp-sumi-k requested changes

2023-02-20 07:39 UTC, cp-sumi-k commented on vue-frontend/src/pages/portfolio/index.vue
> +    <UserReview ref="userReview" class="sm:tw-top-[40px]" />
The top and bottom space of this section is too much. Check it in all devices and make it same as other sections for all devices

2023-02-20 09:52 UTC, cp-sumi-k submitted a review, later dismissed

2023-02-20 09:57 UTC, cp-priyanka-g submitted a review, later dismissed

2023-02-21 08:43 UTC, cp-sumi-k submitted a review, later dismissed

2023-02-21 08:59 UTC, cp-priyanka-g submitted a review, later dismissed

2023-02-21 09:33 UTC, merged