Feat :new CTA section
canopas/canopas-website pull request #339
Opened 2023-03-20 09:15 UTC by cp-mansi-d

**Tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-03-21 07:07 UTC, cp-sumi-k requested changes

2023-03-22 08:38 UTC, cp-priyanka-g commented on vue-frontend/tailwind.config.cjs
> +        underlineOut: "underlineOut 1s",
underline animation looks differ then figma.

2023-03-22 08:39 UTC, cp-priyanka-g commented on vue-frontend/src/components/home/NewCTASection.vue
> +      <img
background image looks blurr.

2023-03-22 08:49 UTC, cp-jagruti-a commented on vue-frontend/src/components/home/NewCTASection.vue
> +        :srcset="`${Cta400} 400w, ${Cta800} 800w, ${Cta1200} 1200w, ${Cta2400} 2400w`"
background image is blur and its circles shapes are getting change in most of devices which is not looking good

2023-03-22 08:52 UTC, cp-priyanka-g commented on vue-frontend/src/components/home/NewCTASection.vue
> +  <div class="tw-relative tw-top-10 sm:tw-top-px tw-pt-12 tw-font-inter-medium">
recheck the font and font-weight

2023-03-22 12:43 UTC, cp-sumi-k submitted a review, later dismissed

2023-03-23 08:40 UTC, cp-priyanka-g approved these changes

2023-03-23 08:40 UTC, cp-jagruti-a approved these changes

2023-03-23 09:09 UTC, cp-sumi-k approved these changes

2023-03-23 09:10 UTC, merged