Redesign justly portfolio page
canopas/canopas-website pull request #350
Opened 2023-04-07 10:23 UTC by cp-jagruti-a

**Tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-04-10 10:10 UTC, cp-sumi-k requested changes

2023-04-10 10:10 UTC, cp-sumi-k commented on vue-frontend/src/portfolio-json/justly-data.js
> +      title: `<span class="border-text">Careful</span> <br/>branding`,
Reduce vertical(top-bottom) space of this title and other titles too

2023-04-11 09:20 UTC, cp-priyanka-g approved these changes

2023-04-11 13:41 UTC, cp-sumi-k submitted a review, later dismissed

2023-04-12 03:43 UTC, cp-priyanka-g approved these changes

2023-04-12 03:44 UTC, merged