Feat:Create what-we-offer section
canopas/canopas-website pull request #355
Opened 2023-04-14 07:12 UTC by cp-priyanka-g

**Tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-04-25 07:33 UTC, cp-sumi-k requested changes

2023-04-25 07:33 UTC, cp-sumi-k commented on vue-frontend/src/components/services/WhatWeOfferDesktop.vue
> +import mobileApp2400w from "@/assets/images/service/mobileapp-2400w.webp";
Do we need 2400 width images, as images renders only in half of the page?

2023-04-25 07:33 UTC, cp-sumi-k commented on vue-frontend/src/components/services/WhatWeOfferSection.vue
> +import mobilApp1200w from "@/assets/images/service/mobileapp-1200w.webp";
Do we need images with > 800 width in mobile devices?

2023-05-03 06:25 UTC, cp-sumi-k approved these changes

2023-05-03 06:54 UTC, cp-sumi-k approved these changes

2023-05-03 08:27 UTC, cp-jagruti-a approved these changes

2023-05-03 08:45 UTC, merged