Design contact us today section of services page
canopas/canopas-website pull request #363
Opened 2023-04-24 05:49 UTC by cp-jagruti-a

## Review checklist

**Note:** Make sure all points should be checked before submiting PR for review, otherwise PR will be cosidered invalid.

- [ ] Follow guidelines for creating branch name, adding commit messages or PR title
- [ ] Add MR description if applicable
- [ ] Follow guidelines for naming conventions everywhere (i.e files/folders, data structures)
- [ ] Reuse code (if the same code is written twice, make it common and reuse it at both places)
- [ ] Remove unused or commented code if not required
- [ ] Make MR self-approved - review MR as a reviewer and give it self-approval if everything is ok, if not make the required changes
- [ ] In progress MR should be marked as draft
- [ ] Make MR mark as ready before submitting it for review
- [ ] Add images, videos, or gifs of UI 
- [ ] Add page speed score screenshot of UI (It should be > 85 for mobile and > 90 for desktops)

**Design should be tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-04-24 08:33 UTC, cp-priyanka-g submitted a review, later dismissed

2023-04-24 08:50 UTC, cp-sumi-k requested changes

2023-04-24 08:50 UTC, cp-sumi-k commented on vue-frontend/src/components/services/ContactUsToday.vue
> +            :srcset="`${contactImages[0]} 400w, ${contactImages[1]} 800w, ${contactImages[2]} 1200w, ${contactImages[2]} 1400w`"
The ideal image width in 30% of the full window width, I think no need to take images> 800 widths in the source set.
you can check the max render the width of images.

2023-04-24 08:50 UTC, cp-sumi-k commented on vue-frontend/src/components/services/ContactUsToday.vue
> +            ><span> Contact Us Today</span></router-link
Adding some effect on hover would be better

2023-04-25 04:28 UTC, cp-sumi-k approved these changes

2023-04-25 04:28 UTC, merged