Implement life at canopas section
canopas/canopas-website pull request #38
Opened 2022-02-02 07:08 UTC by cp-shruti-s

2022-02-03 08:32 UTC, cp-sumi-k commented
Let's use svg instead of webp , also rename directory from `canopas-life` to `life` and images to `jobs_canopas_life_1.svg`

2022-02-03 08:36 UTC, cp-sumi-k requested changes

2022-02-03 08:36 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/LifeAtCanopas.vue
> +// Import Swiper Vue.js components
Remove commented code

2022-02-03 08:36 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/LifeAtCanopas.vue
> +        { id: 1, image: require("@/assets/images/canopas-life/1.webp") },
Let's use svg instead of webp , also rename directory from `canopas-life` to `life` and images to `jobs_canopas_life_1.svg`

2022-02-03 08:36 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/LifeAtCanopas.vue
> +.swiper-pagination-bullet {
I think its duplicate

2022-02-03 08:36 UTC, cp-sumi-k commented on vue-frontend/src/components/partials/ScreenHeader.vue
> +  z-index: 2;
Why do we need to change the z-index?

2022-02-04 11:18 UTC, nidhi-canopas submitted a review, later dismissed

2022-02-04 11:20 UTC, cp-sumi-k approved these changes

2022-02-04 11:45 UTC, cp-sumi-k approved these changes

2022-02-04 11:45 UTC, merged