Design our portfolio section of mobile app development page
canopas/canopas-website pull request #434
Opened 2023-06-26 07:20 UTC by cp-jagruti-a

## Review checklist

**Note:** Make sure all points should be checked before submiting PR for review, otherwise PR will be cosidered invalid.

- [ ] Follow guidelines for creating branch name, adding commit messages or PR title
- [ ] Add MR description if applicable
- [ ] Follow guidelines for naming conventions everywhere (i.e files/folders, data structures)
- [ ] Reuse code (if the same code is written twice, make it common and reuse it at both places)
- [ ] Remove unused or commented code if not required
- [ ] Make MR self-approved - review MR as a reviewer and give it self-approval if everything is ok, if not make the required changes
- [ ] In progress MR should be marked as draft
- [ ] Make MR mark as ready before submitting it for review
- [ ] Add images, videos, or gifs of UI 
- [ ] Add page speed score screenshot of UI (It should be > 85 for mobile and > 90 for desktops)

**Design should be tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-06-29 08:55 UTC, cp-sumi-k requested changes

2023-06-29 08:55 UTC, cp-sumi-k commented on vue-frontend/src/assets/images/mobile-app-development/portfolio/desktop/justly-600w.webp
Any need of 600 widths?

2023-06-29 08:55 UTC, cp-sumi-k commented on vue-frontend/src/components/mobile-app-development/Portfolio.vue
> +              {{ portfolio.title }}
Let's add click events on the title, logo and image on desktop and on image in mobile.

Add hover effect on title: underline should be display on hover from left to right

2023-06-29 08:57 UTC, cp-mansi-d approved these changes

2023-06-29 12:55 UTC, cp-sumi-k requested changes

2023-06-29 12:55 UTC, cp-sumi-k commented on vue-frontend/src/components/mobile-app-development/Portfolio.vue
> +      >
All this title sections are not aligned with figma design, Check it once

2023-06-30 07:40 UTC, cp-sumi-k approved these changes

2023-06-30 07:41 UTC, merged