Feat:Create FaqSection for androidapp development page
canopas/canopas-website pull request #450
Opened 2023-07-14 06:21 UTC by cp-priyanka-g

## Review checklist

**Note:** Make sure all points should be checked before submiting PR for review, otherwise PR will be cosidered invalid.

- [ ] Follow guidelines for creating branch name, adding commit messages or PR title
- [ ] Add MR description if applicable
- [ ] Follow guidelines for naming conventions everywhere (i.e files/folders, data structures)
- [ ] Reuse code (if the same code is written twice, make it common and reuse it at both places)
- [ ] Remove unused or commented code if not required
- [ ] Make MR self-approved - review MR as a reviewer and give it self-approval if everything is ok, if not make the required changes
- [ ] In progress MR should be marked as draft
- [ ] Make MR mark as ready before submitting it for review
- [ ] Add images, videos, or gifs of UI 
- [ ] Add page speed score screenshot of UI (It should be > 85 for mobile and > 90 for desktops)

**Design should be tested on:**
- [ ] Inspector (all iPhones and android devices like samsung, motorola)
- [ ] Desktop (chrome, firefox, safari)
- [ ] Laptop / Macbook  (chrome, firefox, safari)
- [ ] iPhone(safari)
- [ ] Available android devices  (chrome, firefox)
- [ ] iPad(safari)
- [ ] Tablet (chrome, firefox)

2023-07-17 10:23 UTC, cp-sumi-k requested changes

2023-07-17 10:23 UTC, cp-sumi-k commented on vue-frontend/src/components/android-app-development/FaqSection.vue
> +      var len = this.faqs.length / 5;
If 5 is number of faqs then let's use TOTAL_FAQ_IN_SLIDE

2023-07-17 10:28 UTC, cp-jagruti-a requested changes

2023-07-17 10:28 UTC, cp-jagruti-a commented on vue-frontend/src/components/android-app-development/FaqSection.vue
> +    class="tw-mb-[1rem] tw-bg-gradient-to-t tw-from-[#F2709C]/[80%] tw-via-[#FF9472]/[50%] tw-to-white tw-bg-gradient-[1deg] md:tw-container md:tw-bg-none"
this gradient is not looking perfect as it is hiding image in mobile devices do it according to figma you can add it according to figma in config file to use all colors

2023-07-17 10:28 UTC, cp-jagruti-a commented on vue-frontend/src/components/android-app-development/FaqSection.vue
> +              type="button"
reduce space between arrows in mobile devices

2023-07-18 07:01 UTC, cp-jagruti-a approved these changes

2023-07-18 07:02 UTC, merged