Footer-Section
canopas/canopas-website pull request #55
Opened 2022-02-14 06:58 UTC by cp-priyanka-g

Responsive footer section.

2022-02-14 09:15 UTC, cp-sumi-k requested changes

2022-02-14 09:15 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/FooterSection.vue
> +.normal-text {
We do not have to write css for normal-text again as it is already in app.vue

2022-02-14 09:15 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/FooterSection.vue
> +      <h4 class="normal-text">Follow us on</h4>
Why do we need to wrap it in the `h4` tag? I think div is better

2022-02-14 09:15 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/FooterSection.vue
> +  font-size: 15px;
Take font-size in rem

2022-02-14 09:15 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/FooterSection.vue
> +.social-media-icons li:hover {
Make social-media-icon as gradient-btn. On hover, it will behave like `Let's talk business` button of header

2022-02-14 09:15 UTC, cp-sumi-k commented on vue-frontend/src/components/jobs/FooterSection.vue
> +  <footer class="bottom-footer-div">
We need to add background image also

2022-02-16 10:27 UTC, cp-shruti-s commented on vue-frontend/src/components/partials/ScreenFooter2.vue
> +        <img src="@/assets/images/footer/glassdoor.webp" class="glassdoor-img" />
Images  should be define in a data variable

2022-02-21 10:30 UTC, cp-sumi-k approved these changes

2022-02-22 04:39 UTC, cp-sumi-k approved these changes

2022-02-22 04:44 UTC, cp-shruti-s approved these changes

2022-02-22 09:16 UTC, merged