Implement unit test for jobs API
canopas/canopas-website pull request #78
Opened 2022-03-02 06:12 UTC by cp-shruti-s

2022-03-02 09:54 UTC, cp-sumi-k requested changes

2022-03-02 09:54 UTC, cp-sumi-k commented on jobs/jobs_test.go
> +
We need to write test for `send-career-mail` also

2022-03-02 09:54 UTC, cp-sumi-k commented on utils/test.go
> +func nullString(value string) null.String {
What is use of this function?

2022-03-02 09:54 UTC, cp-sumi-k commented on jobs/jobs_test.go
> +		},
Is this method testing  `/api/careers/:id` api?

2022-03-02 09:54 UTC, cp-sumi-k commented on jobs/jobs_test.go
> +	utils.PrepareTablesData(testDB)
Shouldn't we have to insert data before running the test?

2022-03-02 11:46 UTC, jimmy0251 commented
Let's also run the test on CI to make sure they are passing!

2022-03-04 09:41 UTC, jimmy0251 submitted a review, later dismissed

2022-03-05 04:52 UTC, cp-sumi-k submitted a review, later dismissed

2022-03-05 05:00 UTC, cp-sumi-k approved these changes

2022-03-05 05:00 UTC, merged